### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/bench#1]
Copied from https://github.com/lampepfl/dotty/pull/2884

Suggestions:
 - [x] measure in milliseconds;
 - [x] graph multiple lines:
   - average
   - [x] median [50% percentile]
   - 5% percentile
   - 95% percentile
   - 99% percentile
   - trendline for all listed above
 - [x] store raw data for runs, so that we don't need to rerun benchmarks.

 - [x] add a test that is supposed to always be flat, will be used as indicator of stability of machine.

- [x] make the Y axis start from 0

- One more suggestion: could you align the x axis across multiple benchmarks? so that one vertical always relates to the same PR on all benchmarks.

**Comment by liufengyun** [comment]
@DarkDimius Currently the data format is as follows:

```
key, PR, time, commit, avg, error, confidence, test_time
projects/dotty, 2886, Wed Jul 19 22:08:53 2017 +0200, 9b99107, 23216650.756500, 591455.312592, 99.9%, Thu 20 Jul 2017 06:54:21 +0200
```

I can add another column `warmups` and `runs` to hold a list of _space separated_ raw values like `50.1 60.8 73 90`:

```
key, PR, time, commit, avg, error, test_time, warmups, runs
projects/dotty, 2886, Wed Jul 19 22:08:53 2017 +0200, 9b99107, 23216650.756500, 50, Thu 20 Jul 2017 06:54:21 +0200, 50 60 70 80 90, 10 12 12 13 14
```
I'm not sure if that address your concern?  

Note: Now _confidence_  are not useful, I removed it. I want to keep `avg`, as it helps people who read the csv file directly.

**Comment by DarkDimius** [comment]
> I'm not sure if that address your concern?

It does, thank you!

**Comment by liufengyun** [comment]
Regarding warmups:

> you give either 5 runs or 5 minutes, whatever is greater

**Comment by DarkDimius** [comment]
and the same for run iterations: 20 runs or 10 min, whatever is greater
