### ISSUE TITLE
scalapb benchmark has no new points since 20/9

### ISSUE THREAD

**Issue by smarter** [liufengyun/bench#59]
See http://dotty-bench.epfl.ch/

**Comment by liufengyun** [comment]
It's disabled because Dotty has a regression after native apply
refactoring. I'll have to investigate the cause.

Le 30 sept. 2017 4:25 PM, "Guillaume Martres" <notifications@github.com> a
écrit :

**Comment by smarter** [comment]
ah ok, I think @allanrenucci is looking at that.
