### ISSUE TITLE
Ability to zoom in or set a start date for the graphs ?

### ISSUE THREAD

**Issue by smarter** [liufengyun/bench#62]
There are now a lot of points on http://dotty-bench.epfl.ch/ this is good :), but it makes a bit hard to see what's happening in the last few points. It'd be great if we could ignore points before a start date, or zoom in to some points.

**Comment by liufengyun** [comment]
Ignore points or use logarithmic points should work.

**Comment by liufengyun** [comment]
Implemented and deployed in https://github.com/liufengyun/bench-web/pull/2
