### ISSUE TITLE
support multiple lines in chart

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/bench#67]
Multiple lines in chart is common feature in data visualization. We'd like to investigate changes to support this:

- data-format change
- front-end display
- existing data migration

**Comment by liufengyun** [comment]
One tricky issue is that, the points are not indexed by:

- date
- PR
- commit

The same PR may be tested several times, thus have several points. The same commit could also be tested multiple times to check variance of the test.

One approach is to just allow one point for one commit, this way, the lines can align on commits (if we ignore sampling problem).

At the data-generating part, it has to either override the test data for existing commit, or disallow test for existing commit, both are not the good things to do.

**Comment by liufengyun** [comment]
According to discussion with @nicolasstucki , it seems we need to introduce a test session number, and use `(commit, test-session-no)` as the align key.

**Comment by liufengyun** [comment]
Another choice is to port the Scalac benchmarks: https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark . So that we can have another benchmark on a different machine to validate each other.

The Scalac benchmark was designed without supporting continuous integration, thus it's easier to have multiple compile targets.

Different benchmark frameworks have different designs, it's really difficult to have all features in one product, especially when the model doesn't fit. Changing the model is only justified if the change doesn't harm the generality and integrity of the model. Otherwise, it will compromise maintenance and stability of the existing system.

WDYT @nicolasstucki ?

**Comment by nicolasstucki** [comment]
I like the idea of porting the Scalac benchmarks. I believe it is more important to have comparisons on multiple compiler targets/setting.

**Comment by liufengyun** [comment]
Yes, that simplifies things a lot, as they can just set `x-axis` to `time`, which we cannot do.

**Comment by liufengyun** [comment]
Close this, we decided to put things in different charts. As we have the data, it's possible to have some other charts that show data _by time_, thus it's possible to have them in one chart.
