### ISSUE TITLE
To many data points on the X axis

### ISSUE THREAD

**Issue by nicolasstucki** [liufengyun/bench#768]
Now that we have benchmarked for a while, if we ask all the points the graph becomes too dense to see or select points.

Some possible solutions:
  * Add a way to scroll the X axis and make it expand liberally with the time we have been benchmarking
  * Show all points in range of dates

**Comment by liufengyun** [comment]
Thanks for the suggestion. Indeed it's a problem. I'll see if we just switch to a better charting library.
