### ISSUE TITLE
bench points to the wrong PR

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/bench#8]
The latest speedup most likely comes from https://github.com/lampepfl/dotty/pull/2896 -- due to some reordering of the commits, the graph doesn't point to the correct PR.

**Comment by nicolasstucki** [comment]
They might come from lampepfl/dotty#2915

**Comment by liufengyun** [comment]
Or, might be from both -- previously when there's `lazy`, the curve for `Vector` doesn't change.

**Comment by liufengyun** [comment]
The last tested merge is 2884, so it seems it cannot be 2915. I'm triggering it now to see if `2915` produces further drop.

**Comment by liufengyun** [comment]
I'm re-running the benchmarks now for today -- it seems the cause is that I rebooted the testing server, the quotas on CPU get lost, so the machine becomes faster.

Now I restored the quotas on CPUs, and it's running again.

**Comment by liufengyun** [comment]
The tests finished, it confirms the cause is due to the lost of the CPU setting. Now the points on the graph look reasonable.
